---
- name: Installing wordpress dependencies
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
  # Mandatory for installing Wordpress
  - php7.0-mysql 
  tags: wordpress_install-dependencies

- include: install-wordpress.yml
  tags: wordpress_install-wordpress

- include: add-wp-config.yml
  tags: wordpress_add-wp-config

- include: download-wordpress.yml
  tags: wordpress_download-wordpress

- include: install-plugins.yml
  tags: wordpress_install-plugins

- include: install-local-plugins.yml
  tags: wordpress_install-local-plugins

- include: import-uploads.yml
  tags: wordpress_import-uploads

- include: export-uploads.yml
  tags: wordpress_export-uploads